### ISSUE TITLE
Generics limitations

### ISSUE THREAD

**Issue by raulraja** [MichaelRocks/lightsaber#4]
I find this library very interesting for our current work in Arrow http://arrow-kt.io/ around resolving type class instances at compile time.

I'd like to ask you about the real limitations in resolving generic expressions:

https://github.com/MichaelRocks/lightsaber#generic-injection

The kind of dependency injection we are looking to solve at compile time looks something like this:
```
interface Functor<F> {
  fun map(fa: HK<F, A>, f: (A) -> B): HK<F, B>
}
object OptionFunctorInstance : Functor<OptionHK> {
  override fun map(fa: OptionKind<A>, f: (A) -> B): Option<B> = ...
}

functor<OptionHK>() // Compiles because there is a `Functor<Option>` provided
functor<List>() // Does not compile because there is no `Functor<List>` provided
```

Can we use lightsaber for something like this?

Thanks again for a great library!

**Comment by MichaelRocks** [comment]
Hi @raulraja, I believe this case should work. However you should take into account that if you're using [declaration-site variance](https://kotlinlang.org/docs/reference/generics.html#declaration-site-variance) you will need to use [`@JvmSuppressWildcards`](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#variant-generics) in order to make signatures of a generic dependency at the provision and the injection points match each other exactly.
